### ISSUE TITLE
The type of rules cannot be simple primitives

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#101]
While working on #100 I realized that with our current c-parser, the type of rules cannot be simple types that cannot be aliased to pointers. For example, `operator_ty` is a simple integer and the code
generated by the c generator is invalid as integers cannot be assigned to `NULL` and the memoization functions require also `void*`.

I open this issue to discuss how we should proceed in these cases.

**Comment by pablogsal** [comment]
To see what I mean, check how the augmented assignment need to be treated in https://github.com/gvanrossum/pegen/pull/100/files

**Comment by pablogsal** [comment]
As a workaround, I will create a capsule type to hold the integer for https://github.com/gvanrossum/pegen/pull/100

**Comment by lysnikolaou** [comment]
I don't feel that the need for primitive types is strong enough in order for us to do something at this stage. The only two rules that need a capsule type are comparisons and aug assignments (with comparisons it even works better this way, because of the way `_Py_Compare`'s arguments work).

**Comment by gvanrossum** [comment]
Agreed. We’d have to introduce a convention for errors, and zero isn’t necessarily the best. (Many C API functions use -1 for errors, but not all.)

OTOH if the only issue is initializing to NULL, we can probably write that as 0 instead? (void* would be harder to avoid.)

**Comment by lysnikolaou** [comment]
Again, since the grammar is ready, I'd say we go ahead and close this as well.
