### ISSUE TITLE
Propagate errors from grammar actions

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#102]
Currently, we don't have a way to correctly propagate errors in grammar actions helpers as written as these must be written as simple expressions. Solving this is important because these helpers perform many C-API calls that can potentially fail (such as memory allocation, Unicode manipulation...etc) and without explicitly checking for errors these failures will pass unnoticed.

**Comment by pablogsal** [comment]
Check the discussion on https://github.com/gvanrossum/pegen/pull/97 for more context

**Comment by gvanrossum** [comment]
Since there is always an arena, I wonder if we may be able to resort to setjmp/longjmp? That’s pretty portable these days right?

**Comment by apalala** [comment]
If I understand correctly, why not make the helpers use the current CPython protocol for propagating errors?

If semantic actions must be simple expressions, then they can propagate by returning `NULL`.

For complex expressions in which subexpressions my err, there could be wrappers that check the parts, and and evaluate to `NULL` after setting the error status if something goes wrong.

Another the idea is to augment the grammar-grammar so there may be an error message associated to a semantic action for when the action results in `NULL`.
