### ISSUE TITLE
Reduce the number of `void*`in the c generator

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#104]
There is a bunch of places where we use (probably) too many `void*` types and this stops `gcc` from reporting multiple errors due to passing incorrect `AST` types from one side to the other. Many of the errors that can actually be cough are emitted as warnings. 

In some cases, we know the return type of the function so we known that anything that is assigned to the resulting value (many cases named `res`) must have the same type. 

Another possibility, for the time being, is transform some of the warnings into errors via compiler flags.

The reason I am raising this issue is that debugging these cases almost always implies dealing with segmentation faults that originate from CPython when it tries to make use of some corrupted nodes.

**Comment by lysnikolaou** [comment]
Since the Grammar is ready and appears to be close to bug-free, I'd say we close this.
