### ISSUE TITLE
What should the expressions rule return?

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#106]
Up until now I was under the impression that the `expressions` rule should return either a tuple, if there are multiple expressions or the expression itself, if there only is one.

But trying to refactor the various atom rules, I saw this:
```
set: '{' expressions '}'
```
which means that expressions should return an `asdl_seq *` of all the parsed expressions?

What is the right approach here?

**Comment by gvanrossum** [comment]
Probably separate rules for the separate use cases.
