### ISSUE TITLE
Should rule actions be functions?

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#119]
I have been thinking a bit about the error handling in rule actions and action helpers and I have the proposition of either allowing the c_generator to automatically create functions from whatever you include between the `{` `}` (harder) or to force ourselves into just calling functions defined in the `pegen.c` file or another compilation unit (easier). In this way, we can do proper error handling and teach the C generator to propagate errors. This becomes more and more important as we implement more rules because failures on the helper usually only appear much later as corrupted objects in deallocation procedures or similar.

What do you think?

**Comment by gvanrossum** [comment]
How about my idea from #102, to use setjmp and longjmp when one of our own functions detects an error?

**Comment by lysnikolaou** [comment]
This can probably be closed now that #130 has landed.
