### ISSUE TITLE
Simpy refactorings: class_def and arguments

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#122]

**Comment by lysnikolaou** [comment]
I'm close to completing these refactorings. Only one problem left: I followed Python/ast.c's example and I am constructing a dummy `Call` object when parsing arguments. When doing so I use `CONSTRUCTOR(p)` to construct a dummy name object, which leads to a segfault and upon debugging I found out there is a negative reference count error. Any ideas on how I can solve this? I am not that familiar with reference counting and how things can go wrong. Could there be some bug in `CONSTRUCTOR` or `_create_dummy_identifier`?

**Comment by gvanrossum** [comment]
I wonder if something is not expecting a NAME and just accessing the dummy
name in the belief that it's something else? That would spell sure
disaster, and I could imagine it resulting in a negative refcount.

**Comment by lysnikolaou** [comment]
What would that something be though? The `Call` object gets dumped pretty soon after it's created and it isn't part of the AST when calling `PyAST_mod2obj`.

**Comment by pablogsal** [comment]
My experience with the negative reference count problem is that what's actually happening is that, as @gvanrossum points out something is casted to a Python object from the wrong thing and when the arena destroys that things the obj_refcnt field is garbage. You can use rwatch/watch in gdb and reverse execution to trace the origin of the problem.

**Comment by pablogsal** [comment]
Also, if you point me to a branch I can try to help :)

**Comment by lysnikolaou** [comment]
Some help would be appreciated! It's [this](https://github.com/lysnikolaou/pegen/tree/class-def-args) branch on my fork.

**Comment by lysnikolaou** [comment]
@pablogsal Never mind! I found the bug.

**Comment by pablogsal** [comment]
> @pablogsal Never mind! I found the bug.

Nice! What was the problem, out of curiosity?

**Comment by lysnikolaou** [comment]
Nothing interesting, just passing a `NAME` instead of an identifier to `_Py_keyword`. Sorry for the noise!

**Comment by lysnikolaou** [comment]
@pablogsal There is a bug with the line/col info of starred expressions within function calls. Opened an issue [here](https://bugs.python.org/issue39080) on bpo.

**Comment by lysnikolaou** [comment]
Also pushed a PR: python/cpython#17645

**Comment by gvanrossum** [comment]
> just passing a `NAME` instead of an identifier to `_Py_keyword`

Why doesn't the C compiler's type checking catch that? Is one of the types involved `void *`? Can we tighten that?

**Comment by lysnikolaou** [comment]
> > just passing a `NAME` instead of an identifier to `_Py_keyword`
> 
> Why doesn't the C compiler's type checking catch that? Is one of the types involved `void *`? Can we tighten that?

We could refactor `name_token` to return an `expr_ty`.

**Comment by gvanrossum** [comment]
But name_token already returns expr_ty.

**Comment by lysnikolaou** [comment]
> But name_token already returns expr_ty.

That was a really bad choice of words. What I meant was that we can refactor the generator, so that the variable that holds the return value of `name_token` to be of type `expr_ty`. At the moment, it's `void *`.

**Comment by pablogsal** [comment]
> That was a really bad choice of words. What I meant was that we can refactor the generator, so that the variable that holds the return value of `name_token` is of type `expr_ty`. At the moment, it's `void *`.

This problem can technically affect everything else, no? We always declare the result as `void * res`

**Comment by gvanrossum** [comment]
Hmm, the result should be declared using the type of the rule.

**Comment by lysnikolaou** [comment]
Also there is still a reference count error in the newest version, when trying to parse `Lib/test/test_grp.py`, which I don't know the reason for.

**Comment by pablogsal** [comment]
> Hmm, the result should be declared using the type of the rule.

Actually, looking closer that already happens when `rule.type` is populated.

**Comment by lysnikolaou** [comment]
> We always declare the result as `void * res`
> except for `asdl_seq`.

What I meant was the intermediate variable that holds the return value of `name_token`. That wouldn't create a problem and we could then avoid things like casting to `expr_ty`, when we need its identifier.

**Comment by pablogsal** [comment]
> What I meant was the intermediate variable that holds the return value of `name_token`. That wouldn't create a problem and we could then avoid things like casting to `expr_ty`, when we need its identifier.

Oh, I see. But that can happen in intermediate rules as well. For example:

```
import_from_as_name[alias_ty]:
    | a=NAME b=['as' z=NAME { z }] { _Py_alias(((expr_ty) a)->v.Name.id,
                                               (b) ? ((expr_ty) b)->v.Name.id : NULL,
                                               p->arena) }
```

that generates a temporary rule that grabs the result of b as void*.

**Comment by lysnikolaou** [comment]
> Oh, I see. But that can happen in intermediate rules as well. For example:
> 
> ```
> import_from_as_name[alias_ty]:
>     | a=NAME b=['as' z=NAME { z }] { _Py_alias(((expr_ty) a)->v.Name.id,
>                                                (b) ? ((expr_ty) b)->v.Name.id : NULL,
>                                                p->arena) }
> ```
> 
> that generates a temporary rule that grabs the result of b as `void*` so even if the temporary variable is not `void*` the whole temporary rule should return the appropriate type so the information is not lost.

That's true. 

As a first step I think it would be good to change the generator to generate `expr_ty` variables for calls to `name_token`, which seems easier and would be an improvement by itself. And then we can also see if we can also refactor the generator to identify the return type for intermediate rules  such as the one in your example.

**Comment by lysnikolaou** [comment]
Also @pablogsal, would you be able to help out with the reference count error mentioned in my comment [here](https://github.com/gvanrossum/pegen/issues/122#issuecomment-566785684)? It's on [this](https://github.com/lysnikolaou/pegen/tree/class-def-args) branch.

**Comment by pablogsal** [comment]
> Also @pablogsal, would you be able to help out with the reference count error mentioned in my comment [here](https://github.com/gvanrossum/pegen/issues/122#issuecomment-566785684)? It's on [this](https://github.com/lysnikolaou/pegen/tree/class-def-args) branch.

On it!

**Comment by pablogsal** [comment]
> Also @pablogsal, would you be able to help out with the reference count error mentioned in my comment [here](https://github.com/gvanrossum/pegen/issues/122#issuecomment-566785684)? It's on [this](https://github.com/lysnikolaou/pegen/tree/class-def-args) branch.

Is actually `test_grammar.py` the one that has the problem, not `test_grp`. To check this, try to parse only that file (`test_grammar.py`) or just delete the other and see it fail with whatever test runs after `test_grammar.py`.

**Comment by pablogsal** [comment]
This is enough to make it fail:

```
with A() as (x,y):
    pass
```

**Comment by lysnikolaou** [comment]
Oh yes, you're right! I don't really know how the changes in that branch could have caused this, but this certainly makes the point that a solution to #103 is needed.

**Comment by pablogsal** [comment]
Oh yes, you're right! I don't really see how the changes in that branch could have caused this,

Apparently, that has been there since 3a449fc72d0f8ae587a6aa8aef018bac8a4ca810

**Comment by lysnikolaou** [comment]
At the time, `targets` could only handle a NAME. It is in #87 that the `targets` rule was refactored and this was introduced.

**Comment by pablogsal** [comment]
> At the time, `targets` could only handle a NAME. It is in #87 that the `targets` rule was refactored and this was introduced.

Maybe I am missing something, but checking out that commit and test it with Python debug segfaults:

```
> git checkout 3a449fc72d0f8ae587a6aa8aef018bac8a4ca810

> python -m pegen data/simpy.gram -c -o parse.c  --compile-extension && python -c 'import parse; parse.parse_string("with A as (x,y,z):  pass")'

./Include/object.h:541: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x55a3c214edf0 is freed>
Fatal Python error: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x00007f5670d51740 (most recent call first):
  File "<string>", line 1 in <module>
[1]    34014 abort (core dumped)  python -c 'import parse; parse.parse_string("with A as (x,y,z):  pass")'
```

**Comment by lysnikolaou** [comment]
Yeah, not sure why, since `target` would return a dummy name, in case a tuple was parsed.

In any case, I have something ready for #103, which is in no way perfect but I think it is a step towards the right direction. I'll open a PR shortly.
