### ISSUE TITLE
Handle reserved words like the old parser

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#152]
In the old parser, reserved words (e.g. `if`) are *always* reserved. We should mimic this behavior for most keywords, otherwise people will start abusing the feature. But there should be a way to turn it off for specific situations, to support e.g. `async def` and `await` (and in the future to support other "compound keywords", like `match of`, if we want to go there).

**Comment by lysnikolaou** [comment]
We can keep an array of all the reserved keywords in `pegen.c` and check against it every time `name_token` is called. Is that what you mean?

This has some runtime implications though, as this means we will have 36 iterations of a loop every time `name_token` gets called with a NAME.

**Comment by gvanrossum** [comment]
Yeah, that's what the original parser also seems to do -- see `classify()` in `Parser/parser.c`. There's a list of keywords in `g->g_ll.ll_label` which is initialized in `Python/graminit.c`: `static const label labels[...]` near the end. (It's a sparse array even!)

**Comment by lysnikolaou** [comment]
@gvanrossum A question that I cannot find the answer to, when implementing your suggestion from #169, is how to generate the token types from c_generator and have them be accessible from within pegen.c? Would hard coding the token types in both places be okay or should we do something else?

**Comment by gvanrossum** [comment]
The code generator could put them in a static array and call an init function in pegen.c passing it a pointer to the array. That init function would then put the pointer in a static global. Or maybe the pointer could be in the Parser struct.
