### ISSUE TITLE
“make simpy_cpython” fails on Ubuntu and with Python built from source

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#154]
I just found out that `make simpy_cpython` fails on my Ubuntu machine, because the Python version I'm using was build from source `--with-pydebug` and [this](https://github.com/python/cpython/blob/3f12ac18a407983a23d43ae785e805e773571477/Objects/typeobject.c#L3155) assertion fails in `Objects/typeobject.c`.

I think that the file and line that's causing the failure is `Lib/multiprocessing/pool.py` [on line 517](https://github.com/python/cpython/blob/3f12ac18a407983a23d43ae785e805e773571477/Lib/multiprocessing/pool.py#L517).

It seems that this is somehow related to `a = [*b()]` failing to parse at the moment with a `ValueError: field value is required for Starred`, which I cannot figure out the reason for. Any ideas?

**Comment by gvanrossum** [comment]
The assert means that some C code for is receiving a NULL  it doesn’t check for it, and the error code is saved until some other C code enters that assert. You should look at the generated code that is supposed to parse that syntax.

This may be hard to fix (though essential): there may be a failure such as allocation that is interpreted as a parse failure — both use NULL to flag failure.

**Comment by lysnikolaou** [comment]
Some findings until now:

A consistent way to reproduce this assertion failure is to first parse `a = [*b()]` with `ast.parse(...)` and then with `parse.parse_string(...)`. In this scenario we get on of the following two alternatives:
1. 
```
Fatal Python error: a function returned a result with an error set
Python runtime state: initialized
ValueError: field value is required for Starred

The above exception was the direct cause of the following exception:

SystemError: <built-in function parse_string> returned a result with an error set
```
2. `python: Objects/typeobject.c:3123: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.`

In case `ast.parse(...)` does not get called, then I (almost [?], not sure) always get the same thing: `ValueError: field value is required for Starred`.

**Comment by pablogsal** [comment]
The problem is that in

```
star_target[expr_ty]:
      | '*' a=bitwise_or { _Py_Starred(set_expr_context(p, a, Store), Store, EXTRA) }
```

`set_expr_context` is returning NULL. I think to detect this better we need #102 ...

**Comment by pablogsal** [comment]
> `set_expr_context` is returning NULL. I think to detect this better we need #130 ...

And that happens because the `switch (expr->kind) ` in `set_expr_context` is not handling `Call_kind`.

**Comment by pablogsal** [comment]
Actually, I think we need to handle all the missing types that can be in that situation. For example:

```
[*(yield x)]
```

will fail as well.

**Comment by lysnikolaou** [comment]
That's it, yes! Thanks for the help, @pablogsal!
