### ISSUE TITLE
Better tests for mutual left-recursion in C generated parsers

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#158]
There is a suspicion that the generated code (or the support code) for mutually left-recursive rules is broken in C. It would be good to at least test this using the same tests as used to test this for the Python generator.

Those tests are at https://github.com/gvanrossum/pegen/blob/master/test/test_pegen.py#L376-L444.

**Comment by pablogsal** [comment]
At least the first one is tested here:

https://github.com/gvanrossum/pegen/blob/master/test/test_c_parser.py#L146-L153

**Comment by pablogsal** [comment]
Opened https://github.com/gvanrossum/pegen/pull/159 to add the missing test (`test_nasty_mutually_left_recursive`).

**Comment by gvanrossum** [comment]
Closed by #159
