### ISSUE TITLE
Ideas for optimizing the grammar

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#172]
(From @apalala)

The characteristics of performance problems in a grammar are too many failed options/rules, and failed options with tracebacks that are very deep.

Applying the "cut" expression should take care of most problems, because we know Python remains LL(small-K).

For later, option reordering is a common way to optimize. Options that produce the most "hits" should come first in rules and groups. 

The above is a combination of failing early (cut), and succeeding early.

**Comment by apalala** [comment]
Lookeheads help when there's ambiguity, but I think that the only tough part of Python to parse right now is argument lists (both `def` and call).
