### ISSUE TITLE
change grammar file extension from .gram to something lexers know about

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#178]
@gvanrossum originally use `.gram`, but `.ebnf`, `.peg`, etc. have a better chance to be picked up by editors and IDEs.

This relates to #161

**Comment by gvanrossum** [comment]
If you want to change this, please collect *facts*, for example what extensions are supported by IDEs that are popular with Python coders -- either out of the box or with a well-known extension (e.g. in the "marketplace"). Like PyCharm, Sublime, Emacs, Vim, VS Code. What do these support?

**Comment by lysnikolaou** [comment]
Although I haven't done any research on this, I guess that one "problem" about this is that we don't use the standard PEG notation, which means that IDEs that only support that, will incorrectly highlight our grammar files. If that's indeed the case and someone has to write/extend a new/existing extension for highlighting our grammars, the file extension wouldn't be much of a problem.

**Comment by gvanrossum** [comment]
The current notation is in widespread use for the description of Python, so I'd rather not change.

**Comment by lysnikolaou** [comment]
Me neither. I was just thinking out loud.
