### ISSUE TITLE
F-string support

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#180]
We still don't support f-strings -- an AST is generated with the string constant `"f-strings not supported yet!!"`.

(This is what's left over of #127.)

**Comment by pablogsal** [comment]
@lysnikolaou What do you think if I open a WIP PR to work together on this? With care, we could both push to the PR to iterate. This requires a non-trivial amount of work and I feel I don't have as much time as I wanted so we could finish it together to speed things up

**Comment by lysnikolaou** [comment]
> @lysnikolaou What do you think if I open a WIP PR to work together on this? With care, we could both push to the PR to iterate. This requires a non-trivial amount of work and I feel I don't have as much time as I wanted so we could finish it together to speed things up

Of course! Go ahead and open a PR and let's talk the details over there.
