### ISSUE TITLE
Incorrectly parses imaginary literals

### ISSUE THREAD

**Issue by ethanhs** [gvanrossum/pegen#196]
For `1j` pegen parses it as `1+0j`

**Comment by lysnikolaou** [comment]
@pablogsal Have you already started with this? I just started 5 minutes ago and have a PR ready, but I'm not sure it's right.

**Comment by pablogsal** [comment]
I have a PR already, I am finishing it :)

**Comment by lysnikolaou** [comment]
OK, you go ahead then!
