### ISSUE TITLE
AnnAssign simple is wrong on attribute/subscript assignments

### ISSUE THREAD

**Issue by isidentical** [gvanrossum/pegen#205]
I was testing pegen against astor's (an ast unparser) test suite and I found only one small thing missing, which is pretty cool because astor's test suite is pretty mature.
```py
    ('annotated_assignment_with_attr', 'a.b: int'),
    ('annotated_assignment_with_subscript', 'a[b]: int'),
```
`simple` field of these nodes are `1`, but they should be `0`.

**Comment by lysnikolaou** [comment]
Closed via #206.
