### ISSUE TITLE
Improve memory usage

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#220]
In order to get the performance of pegen closer to the original parser, we need to profile and improve memory usage. This can be achieved now that we have 100% AST coverage (modulo some small tweaks with column and line numbers) so we don't expect big refactorings that will introduce object creation.

- [ ] Benchmark the current pegen master against the CPython parser.
- [ ] Identify/research a method to pinpoint what creates more memory to get improvement opportunities.
- [ ] Iterate until we get as close as we can to the original parser memory usage.

**Comment by gvanrossum** [comment]
I suspect that one of the most useful techniques will be to selectively disable the memoization cache for certain situations. At least, some early feedback I received when I blogged about PEG was that the memoization is wasteful (it is of course also essential in some cases, so we'll have to be careful).

What kind of memory profiling tools do we have?

**Comment by pablogsal** [comment]
> What kind of memory profiling tools do we have?

In the past, I have used Massif (https://valgrind.org/docs/manual/ms-manual.htmt) but I certainly would need to re-learn how to use it as I only used it once or twice.

**Comment by ethanhs** [comment]
I have used https://pypi.org/project/memory-profiler/ before, but that may not exactly lend itself to C code.

**Comment by gvanrossum** [comment]
I did a quick experiment, disabling memoization for all rules (except left-recursive ones, which need it). This reduced the memory usage quite a bit, but also slowed parsing down. But it confirms my hunch that we need to tone down the memoization. My next experiment will be to instrument the memoization to see which rules, if any, are ever used from the memo.

**Comment by gvanrossum** [comment]
OK, so the vast majority of the cache hits are due to left-recursive rules (the top one being `term`), and we can't touch those, since the left-recursion implementation depends on the memoization cache.

The first non-left-recursive cache hit is `atom`, with an order of magnitude fewer hits than `term`. I'm going to change my instrumentation to measure the size of the thing being cached (probably just the number of tokens, since that's the only number I have easily available).

**Comment by pablogsal** [comment]
> OK, so the vast majority of the cache hits are due to left-recursive rules (the top one being `term`), and we can't touch those, since the left-recursion implementation depends on the memoization cache.

What workload are you using to test? Parsing the standard library?

**Comment by gvanrossum** [comment]
Just one file for now -- Lib/tkinter/__init__.py.

**Comment by gvanrossum** [comment]
I now have a small set of targets that need memoization and now compiling `data/xxl.txt` is faster and uses less memory than with the stdlib compiler. Gotta go before I land this though.

**Comment by pablogsal** [comment]
Nice!

**Comment by gvanrossum** [comment]
And landed (I have some time after all).

**Comment by gvanrossum** [comment]
After some tweaks, I have the following results on my Mac:

## Compiling `data/xxl.txt`
With pegen (`make time`):
```
        1.25 real         1.00 user         0.24 sys
 714276864  maximum resident set size
    193384  page reclaims
```
With stdlib (`make time_stdlib`):
```
        1.44 real         1.16 user         0.26 sys
 876003328  maximum resident set size
    217735  page reclaims
```

## Compiling `cpython/Lib/tkinter/__init__.py`
(Why this file? It's one of the largest .py files in the stdlib.)

With pegen (`make time TIMEFILE=cpython/Lib/tkinter/__init__.py`):
```
        0.05 real         0.04 user         0.00 sys
  16334848  maximum resident set size
      4463  page reclaims
```
With stdlib (`make time_stdlib TIMEFILE=cpython/Lib/tkinter/__init__.py`):
```
        0.04 real         0.03 user         0.00 sys
  14909440  maximum resident set size
      4167  page reclaims
```

## Comparison: compiling `data/xxl.txt` with pegen on the master branch
```
        2.01 real         1.40 user         0.39 sys
1136324608  maximum resident set size
    296430  page reclaims
```

## Comparison: ditto tkinter
```
        0.05 real         0.04 user         0.01 sys
  22065152  maximum resident set size
      5865  page reclaims
```

## Conclusion
For the tkinter file we still are a little behind, but much less than before, and this is a universal improvement over the master branch. I need to clean it up before we can merge. (Do we want to keep the instrumentation? It currently uses globally visible names.)

**Comment by lysnikolaou** [comment]
That's great news. 

> Do we want to keep the instrumentation? It currently uses globally visible names.

I'd say we keep the instrumentation.

**Comment by gvanrossum** [comment]
OK, I'll refactor the instrumentation to a cleaner API.

Next, I did a quick hack in the metagrammar: putting a `~` in front of the rule name at the start of the rule turns on memoization for that rule. (This is a no-op for left-recursive rules, which always use memoization, but in a somewhat different way.)

So it looks like this:
```
~expression[expr_ty]:
```

Maybe we should reconsider this syntax. I tend to search the file for the definition a given rule using `^rulename`, so it would be better to have the marker somewhere else. Here are a few options:

1. `expression*[expr_ty]:`
2. `expression[expr_ty]*:`
3. `expression[expr_ty]!:`
4. `expression[expr_ty](memo):`

The last, verbose option (4) would be useful if we ever end up adding other flags to rules.

Thoughts?

**Comment by lysnikolaou** [comment]
> Maybe we should reconsider this syntax. I tend to search the file for the definition a given rule using ^rulename

+1

> The last, verbose option (4) would be useful if we ever end up adding other flags to rules.

Even though I hadn't thought of this, now that you mention it, it might indeed be useful in the future. So I'm gonna go with (4).

**Comment by pablogsal** [comment]
> The last, verbose option (4) would be useful if we ever end up adding other flags to rules.

I like this for its extensibility as well. The rest are easily missed if you are not looking carefully IMHO

**Comment by gvanrossum** [comment]
I think I've finished off the low-hanging fruit. We should decide -- do we want to spend more time optimizing the code (probably this means profiling our C code carefully and looking for bottlenecks) or should we declare victory and close this issue?

**Comment by pablogsal** [comment]
I would be happy to close this one and maybe open more specific issues in the future if we found some other opportunities after benchmarking the C code. But after your latest changes, it seems that we are now in a much better position :tada:

**Comment by lysnikolaou** [comment]
I'm also for closing this one!

> But after your latest changes, it seems that we are now in a much better position

Indeed. Our proposal got a lot stronger with this!!
