### ISSUE TITLE
Integration: Parenthesized with statements are currently allowed

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#229]
Do we want to continue to allow them in CPython as well? If so, we probably need to open a discussion in python-dev and author a PEP, right?

**Comment by gvanrossum** [comment]
Hm, this cannot be done using the old parser, so I would hold off until the old parser is truly dead. Hopefully we can do this in 3.10.

**Comment by pablogsal** [comment]
There is already an opened issue (https://bugs.python.org/issue12782) and up to the points I know everyone agrees that is a desirable thing to do. We can mention this at the language summit talk certainly.

**Comment by lysnikolaou** [comment]
Can be closed as well. It was discussed in python/cpython#19704.
