### ISSUE TITLE
Maybe we don't need black in scripts/show_parse.py

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#230]
I just discovered that `ast.dump()` has a flag `indent=4` which pretty-prints the tree. This will be much faster than running black, so that running `make simpy_cpython` and `scripts/test_pypi_packages.py` should be much faster if there are any differences detected.

**Comment by lysnikolaou** [comment]
But only in 3.9, right?

**Comment by gvanrossum** [comment]
Oh, you're right, it is brand new. Never mind then. :-(
