### ISSUE TITLE
VS Code Syntax Highlighting

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#231]
I developed an extension for VS Code, so that .gram files get syntax highlighting. Any feedback is more than welcome, in case someone uses VS Code.

Repo: https://github.com/lysnikolaou/pegen-peg-highlighting
VS Code Marketplace: https://marketplace.visualstudio.com/items?itemName=lysnikolaou.pegen-peg

**Comment by pablogsal** [comment]
Wow this is super cool! Great job 👌

**Comment by gvanrossum** [comment]
Nice! Maybe I should spend all this time I'm asked to stay at home to develop an Emacs version. :-)

**Comment by lysnikolaou** [comment]
> Nice! Maybe I should spend all this time I'm asked to stay at home to develop an Emacs version. :-)

For me it certainly was a fun way to spend some of my time at home.

**Comment by gvanrossum** [comment]
Hope you are all okay!

**Comment by lysnikolaou** [comment]
Same goes out from me to you all. Stay healthy!

**Comment by pablogsal** [comment]
Yeah, same here! Hopefully, we can meet together in person at some point this year if the situation improves

**Comment by gvanrossum** [comment]
Do you want to keep this issue open?

**Comment by lysnikolaou** [comment]
Nope.
