### ISSUE TITLE
Windows support :(

### ISSUE THREAD

**Issue by ethanhs** [gvanrossum/pegen#46]
Unfortunately it appears that some needed functions are not exported by CPython, thus are unavailable on Windows.

```
pegen.obj : error LNK2001: unresolved external symbol _Py_asdl_seq_new
pegen.obj : error LNK2001: unresolved external symbol PyAST_mod2obj
pegen.obj : error LNK2001: unresolved external symbol PyTokenizer_Free
pegen.obj : error LNK2001: unresolved external symbol PyTokenizer_FromString
pegen.obj : error LNK2001: unresolved external symbol PyTokenizer_Get
pegen.obj : error LNK2001: unresolved external symbol _Py_Name
pegen.obj : error LNK2001: unresolved external symbol PyTokenizer_FromFile
pegen.obj : error LNK2001: unresolved external symbol _Py_Constant
parse.obj : error LNK2001: unresolved external symbol _Py_BinOp
parse.obj : error LNK2001: unresolved external symbol _Py_Module
parse.obj : error LNK2001: unresolved external symbol _Py_Call
parse.obj : error LNK2001: unresolved external symbol _Py_Expr
parse.obj : error LNK2001: unresolved external symbol _Py_If
parse.obj : error LNK2001: unresolved external symbol _Py_Pass
```

This isn't really a request for support, just mentioning this. Ideally pegen gets upstreamed soon :P

**Comment by gvanrossum** [comment]
Thanks for calling this out. It seems that (fortunately) Windows is unique in this respect, so we can still prototype the new parser as an extension module using Linux or Mac.

Unfortunately it will be a long while before I feel comfortable adding this to the core CPython code base -- I would want to have complete actions for the entire grammar (data/simpy.gram).

I guess there could be some kind of transitional phase where pegen in incorporated in cpython but is not used as the default parser yet. We can then continue to refine it there.

But I really want to be able to translate the whole language first. There are also other loose ends, e.g. pegen doesn't support reserved words. (Which might eventually become a feature, but I don't think we should do that in 3.9.)

**Comment by ethanhs** [comment]
Looking more around the project I realize that it will be a while before it can be upstreamed.  It's also a possibility that we copy source files just for Windows like typed_ast I suppose. There aren't that many (I think based on a quick look, `asdl.c/h`, `tokenize.c/h`and `Python-ast.c/h` are most of it). And that is mostly auto generated.

**Comment by gvanrossum** [comment]
If you submit a PR that does that I would totally accept it.

**Comment by ethanhs** [comment]
Okay cool, I will hopefully get around to that next week. :)

**Comment by lysnikolaou** [comment]
Since this has stalled for more than 3 months, I think it can be closed. In case you get around to pushing a PR, @ethanhs, we can certainly reopen it.

**Comment by ethanhs** [comment]
Yeah I've been busy with other things so I won't get around to this soon.
