### ISSUE TITLE
Create tests for data/simpy.gram

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#48]
We should add automated tests (and run them on Travis-CI, see `.travis.yml`) that verify that `data/simpy.gram` can parse all of the CPython standard library code.

If there is a CPython checkout at `$CPYTHON`, then this test would be equivalent to running
```
make simpy TESTDIR=$CPYTHON/Lib
```

If getting a CPython checkout in Travis is too slow, we could create a gzipped tarball of just `$CPYTHON/Lib` and check that into the pegen repo, and as part of the test untar it and then run something like the above `make` command.

**Comment by gvanrossum** [comment]
Eventually we should also test with some 3rd party packages.

Note also that there are a few files in the stdlib that don't parse (see https://medium.com/@gvanrossum_83706/peg-at-the-core-developer-sprint-8b23677b91e6). We can use `./test_parse_directory.py --exclude XXX` for this.

**Comment by apalala** [comment]
I'll take the Travis-CI automation.

As to the files that don't parse, most of them are meant **not** to parse (invalid syntax, deprecated stuff, incorrect encoding), so there could be a way to expect specific failures from that set.

Third-party libraries should parse fully (_atainst 3.7 Python_, even if 3.8 is being used to build the parser).

**Comment by gvanrossum** [comment]
Thanks for taking this on. The `test_parse_directory.py` script has an existing `--exclude` flag that we can use to add files to skip -- or we can add an `--exclude-file` flag to specify a file with files to skip (such a file would be easier to update when needed).

**Comment by gvanrossum** [comment]
BTW, why the 3.7 requirement? Is it just because you started from the 3.7 Grammar/Grammar file?

**Comment by apalala** [comment]
The 3.7 requirement is because we can't on third-party libraries to have upgraded to 3.8. I haven't checked if there are no backwards-incompatible changes in syntax (how about `def f((a)=None)`?), then we can test to 3.8. 

We can also test to 3.8 using the _exclude_ and _expected-failure_ features mentioned above (and this may be the best choice to not hold-back the grammar refactoring).
