### ISSUE TITLE
Create a test set of not-valid Python

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#50]
A parser’s behavior is not fully tested until it is fed with enough bad input. With PEG in particular, some types of incorrect input may make the parser backtrack a lot (strategically placed 'cut' operators help avoid that).

It may be possible to create such test set automatically, by corrupting some valid programs.

**Comment by apalala** [comment]
How about a `--should-fail=PATTERN` (which name?) option in `test_parse_directory.py`?

**Comment by gvanrossum** [comment]
Or maybe just a flag that reverses the condition to "every file should fail". Then we can collect example programs with expected failures in a separate directory.

The more interesting problem is a program that "fuzzes" valid programs to be invalid, using a variety of tricks.

**Comment by apalala** [comment]
I have an initial `failset` from cpython, but somehow I couldn't get `test_parse_directory.py` to exclude the directory from main tests. 

To be safe, I'd change the directory for the `simpy` Makefile target from `.` to `./pegen`.

**Comment by gvanrossum** [comment]
Oh, but we should update that test script so that you can specify a directory to exclude. I don’t like playing games with ‘cd’.

**Comment by gvanrossum** [comment]
We now have FAIL_TEST_CASES is test_ast_generation.py, so this can be closed.
