### ISSUE TITLE
Refactor grammar model

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#54]
The model and the code generators make heavy use of `Rhs`, but RHS in general means just " right hand side", with no hint about the type. In the model `Rhs` is intended to be the right hand side of rules, but the node type of that, after simple optimizations, could be any of the node types `[Cut, Named, StringLeaf, Lookahead, PositiveLookahead, NegativeLookahead, Choice, Alt, Seq, Opt, Repeat0, Repeat1, Group]`.

It's best to drop `Rhs` and stick to the node types that describe types of expressions. That way the visitors, specially the code generators, can have specific actions for each type.

This goes hand in hand with removing synthetic identifiers for expressions in rules, because they complicate the code generators to benefit only toy parsers. Most subexpressions on the right hand side of a rule are discardable, and `name=exp` is enough to explicitly recover the elements relevant to the translation.

**Comment by apalala** [comment]
This refactoring is meant to answer these questions:

* Where are actions allowed in the grammar, and how are they expressed in generated code?
* Where should the variables for named elements be declared in the generated code? What about names within closures?
* How to introduce a 'cut' context for choices, optionals, and closures.

**Comment by gvanrossum** [comment]
Yeah, I think it is a good idea to change this.

I like the model shown in the blog and the code for the blog (story6 or story7 in the pegen repo) better. This model only creates grammar nodes for non-trivial items.

I'm not sure about the wisdom of dropping default names derived from node names. As you say, this obscures toy grammars, but it can also obscure real grammars (I've found many rules have only one of each type). There's not much storage wasted (in the C code) by holding on to unused return values -- the arena allocation code doesn't free or reuse storage until we're ready to delete the entire AST (which won't be until after the bytecode has been generated).

I recommend that you start working on this refactor, even though it will take you longer than me -- it will help you become familiar with the code. Also, I have family activities to attend to and 3-4 presentations to prepare, so I won't be able to spend much focused time on this project. (I can make time several times a day for guidance, but not so much for coding.)

**Comment by apalala** [comment]
OK. I'll work on the refactoring.

You must answer some questions about the grammar design, as the purpose is not (so far) to create a general purpose L->cpython compiler.

* Is any expression allowed within a bracketed expressions (`()`, and `[]`)? In particular are choices (`|`) allowed?
* Where are actions allowed? Note that for our purposes, and given the current C-parser design, they could be allowed _only_ on the alternatives to a rule-level choice (restriction that could be lifted later, if needed).

My objection to synthetic names is that they require a pass through the grammar tree, and that actual parser code generation seems busy taking care of the name of each subexpression. A re-implementation that I would find very acceptable would be for the first pass to manipulate the tree by adding `Named` nodes where appropriate.

**Comment by gvanrossum** [comment]
This is about the metagrammar, right? In theory you could just read the metagrammar -- it's at pegen/metagrammar.gram. :-)

> - Is any expression allowed within a bracketed expressions (`()`, and `[]`)? In particular are choices (`|`) allowed?

Yes. For `( ... | ...)` this is used quite a bit in data/simpy.gram. For `[ ... | ...]` there's only one example, in `assignment` on line 16.

> - Where are actions allowed? Note that for our purposes, and given the current C-parser design, they could be allowed only on the alternatives to a rule-level choice (restriction that could be lifted later, if needed).

The metagrammar allows an action on every alternative. IIRC the process that turns bracketed expressions into new, anonymous grammar rules will do the right thing. (Evidence for this is all the rules with names like `_tmp_60` you can find in the generated parse.c file. These come from `name_node()`, hopefully you can follow the trail back from there.

> My objection to synthetic names is that they require a pass through the grammar tree, and that actual parser code generation seems busy taking care of the name of each subexpression. A re-implementation that I would find very acceptable would be for the first pass to manipulate the tree by adding Named nodes where appropriate.

I've not given performance of the generator much thought, but it looks like this also makes the code more complex and harder to follow. Your proposal sounds fine. I do hope one of us is not confusing this with the process I just described to turn alternatives nested in groups into anonymous rules.

**Comment by gvanrossum** [comment]
This issue seems stalled. I don't think there is much point in keeping it open.
