### ISSUE TITLE
NamedItems with same name must also have the same type in different Alts

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#68]
It seems that due to https://github.com/gvanrossum/pegen/blob/c97dc21f674fa3e7a5fd78bd1df9708fde65fc5c/pegen/c_generator.py#L336 updating the same dict for all alternatives, we cannot have the same variable name have different types in different alts of a rule. Is that so desired?

I discovered it trying to refactor the rules for `import_from` like so:

```
import_from[stmt_ty]:
    | a='from' b=dot_or_ellipsis* !'import' c=dotted_name 'import' d=import_as_names_from { _Py_ImportFrom(get_identifier_from_expr_ty(c), d, seq_count_dots(b), EXTRA(a, d)) }
    | a='from' b=dot_or_ellipsis+ 'import' c=import_as_names_from { _Py_ImportFrom(NULL, c, seq_count_dots(b), EXTRA(a, c)) }
```

It seems reasonable to have the name `c` for different types of rules in both alts.

**Comment by lysnikolaou** [comment]
Never mind! I just figured out that that is actually not possible, or even if it is with the variable being of type `void *` in the C code, it seems worse. Sorry!

**Comment by gvanrossum** [comment]
Agreed. It's definitely something we should document though. (Currently there's no documentation at all, but I'd like there to be some.)

**Comment by lysnikolaou** [comment]
I think, it makes more sense to have the c generator report an error, in case the same variable is used for different node types, rather than just silently go on and assume the last type is the correct one. Thoughts?

**Comment by gvanrossum** [comment]
If you make each alternative its own curly-brace-delimited block you could have independent types. E.g. We currently generate things like
```
    stmt_ty pass_stmt_var;
    ...
    if (
        (pass_stmt_var = pass_stmt_rule(p))
    ) {
        res = pass_stmt_var;
        goto done;
    }
```
Maybe we can change the generator so that it generates this instead:
```
    {
        stmt_ty pass_stmt_var;
        if (
            (pass_stmt_var = pass_stmt_rule(p))
        ) {
            res = pass_stmt_var;
            goto done;
        }
    }
```

**Comment by lysnikolaou** [comment]
> If you make each alternative its own curly-brace-delimited block you could have independent types.

The question is, do we really want to allow that? Like you said in some other issue or PR (can't really remember which one), it'd be good to start naming things somewhat more sensibly in the grammar. If we do that, then the only way this occurs is a typo or a logical error (that's basically just an instinct, but the refactorings for `try`, `for` and `while` have all confirmed it). In this case, it would make sense to just have the generator report an error, cause it could introduce hard-to-find errors otherwise.

**Comment by gvanrossum** [comment]
Well, I disagree with my former self... That sounds like rationalizing a limitation of the code. If we can separate the scopes we should do it.

**Comment by lysnikolaou** [comment]
Ok then!
