### ISSUE TITLE
Refactor Grammar for publishing on Python Docs

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#69]
In case the grammar gets published to the official Python docs, it should be as easy as possible for people to understand it.

This issue should act as a reminder to do the necessary refactoring towards that direction, when/if the grammar gets uploaded.

**Comment by apalala** [comment]
I was going to object to the _dot_ (**`.`**)operator in favor on the docs, but then I thought that one of `pegen`'s output could be a docs-ready grammar. TatSu does grammar->grammar on the pretty-printing feature.

**Comment by gvanrossum** [comment]
Good idea. I am already working on a patch where str() of a grammar strips actions, item names and types; it can also transform `a.b+` into `(b (a b)*)`.

**Comment by lysnikolaou** [comment]
This is also currently discussed in python/cpython#19969, so I'm closing it.
