### ISSUE TITLE
Add custom rule for repetitions separated by another token

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#70]
As noted in #67 the construct `X (sep X)*` gets heavily used by the current grammar, at least 16 times according to a quick search on my editor. It would be a good idea to add a custom rule to handle this construct, so that we don't have to use `seq_insert_in_front` every time, as it creates a brand new `asdl_seq*`. What would the best design be for such a rule?

**Comment by gvanrossum** [comment]
@apalala Juancarlo, do you know if there are precedents for such rules in other PEG implementations?

**Comment by bfoz** [comment]
At the risk of butting into the conversation... would it be possible to add support for macros to the meta-grammar?

```python
my_list = list(itemA, itemB, separator=",")
```

The `list` token could behave like a macro that expands into both the underlying `X (sep X)*` construct as well as the corresponding action for building the list. Or, if the parser were given explicit support for the `list` token, instead of treating it like a macro, the list-building could be performed without tying up the rule's action slot. 

At the very least, it would make the grammar easier to read.

**Comment by gvanrossum** [comment]
@bzof I'm not sure I follow. Let's say today there was a grammar with this rule:
```
expr_list: expr (',' expr)*
```
How would you write that using a macro? I suppose the answer will have to be something like
```
expr_list: LIST(',' expr)
```
or (probably better)
```
expr_list: LIST(expr ',')
```
or perhaps
```
expr_list: (expr ',')LIST
```
for some operator that I'm writing here as `LIST` but for which we could try to come up with a better name. (After all, most other EBNF notation we're using uses postfix operators -- `*`, `+` and `?`.)

I'm not sure how a general macro facility would help here -- I don't expect there to be a whole lot of other applications of such macros. Also, we don't have an existing macro processor lying around (the C preprocessor is way too complex for this problem, and its use of `#` would conflict with our comment notation, and I'm not sure I want to learn how to use m4 again).

**Comment by bfoz** [comment]
That's essentially what I was thinking, but maybe I was over-generalizing by suggesting a full macro processor. And I *definitely* didn't mean to imply that m4 should be brought back from the dead. 

Given how different such a construct would be from standard EBNF, it seems like the prefix-LIST notation might actually be desirable, just to distinguish it from the rest of the notation. OTOH, a readable operator is harder to distinguish from a rule name that happens to be all-caps. So using a more traditional operator symbol might be more appropriate. I'm not sure which one to suggest, though.

Do you have any plans to use angle-brackets or curly-brackets? Perhaps...
```
expr_list: <',' expr>
```

**Comment by gvanrossum** [comment]
Hmm, angular brackets should work. Can you look up in the TatSu docs what
they do? (Use Google to find those docs.)
-- 
--Guido (mobile)

**Comment by bfoz** [comment]
TatSu uses `{}` for repetition, but doesn't appear to use `<>` for anything. Although, I only skimmed the documentation. I haven't taken the time to fully read all if it, yet.

**Comment by lysnikolaou** [comment]
It uses `<` for a left join and `>` for right join though, according to [this](https://tatsu.readthedocs.io/en/stable/syntax.html#op-e) part of the docs.

**Comment by gvanrossum** [comment]
Oh, thanks for the pointer. TatSu has lots of ways to spell this (looks like everything you could possibly want from repetitions :-).

You can take a repetition (which is spelled `{e}`, `{e}+` or `{e}*`, with the first two meaning the same thing) and put one of the following in front of it: `s%`, `s<`, `s>`, or `s.`, where `s` is an atom (or something parenthesized) indicating the separator. All of these parse `e s e s e ...`, with `+` meaning there has to be at least one `e` and `*` meaning there may also be nothing at all.

The difference is in what kind of parse tree is constructed: `%` returns a list containing both `e` and `s` items, `.` returns a list containing the `e` items, and `<` and `>` return left- and right-recursive trees formed of tuples (follow the [link](https://tatsu.readthedocs.io/en/stable/syntax.html#op-e) if you need an example).

We can't blindly copy this though -- in pegen, the parse tree returned is up to the action, and we use `{ ... }` to spell actions. For our C code generator, I'm also not interested in the left/right joins. But maybe we could add the `.` operator to our metagrammar, and arrange for `s.e*` and `s.e+` to return `asdl_seq` objects containing all the `e` expressions captured (this shouldn't be too hard for the C code generator). The Python code generator could produce lists in this case.

We could then write
```
expr_list: a=','.expr+ [','] { a }
```
which would parse a non-empty list of comma-separated expressions with an optional trailing comma and return an `asdl_seq` of the collected `expr`s.

I don't see a strong use case (at least not in the C generator) for TatSu's `%` operator, so I would leave that out.

The downside of this is that it's not very intuitive -- "everybody" has seen `X+` and `X*` before for 1-or-more and 0-or-more repetitions of `X`, but this `.` operator is an invention of TatSu (I think).

So we could also spell this as
```
expr_list: a=LIST(expr ',') [','] { a }
```
which at least has the advantage that you can search the docs more easily for `LIST` than for `.` (imagine that :-).

I would be happy with having a direct spelling for non-empty repetitions only -- the rest we can do using existing operators.

**Comment by gvanrossum** [comment]
We talked off-line, let's use  the `'.'` operator from TatSu:
```
expr_list: a=','.expr+ [','] { a }
```

**Comment by apalala** [comment]
Note that, for consistency, in **pegen** the parenthesis and the finalizing `*` or `+` should be mandatory. I'll review the PR now.

**Comment by gvanrossum** [comment]
Consistency with what though? Pegen's syntax is already different from TatSu. Is there a "standard" PEG syntax? (That said, I think it's indeed a little bit better to require the trailing `+`. We don't plan to implement the `*` version.)

**Comment by lysnikolaou** [comment]
Ok, I'll go ahead and change the code to require the trailing `+`.
