### ISSUE TITLE
Unknown boolop found error, Ideas on how to ignore it for now

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#74]
I'm currently working on getting `BinOp`s, `BoolOp`s and comparisons to work, but I don't really want to refactor the primary rule just yet, which means that if there is something more than just an atom in the expression, `CONSTRUCTOR` gets called, whose result gets propagated up to the `BoolOp`s. I'm assuming that's why I'm getting a `SystemError: unknown boolop found` when running `simpy_cpython`. Any ideas on how we could circumvent this for now?

**Comment by gvanrossum** [comment]
Start with the primary rule instead? :-)

More seriously, you can probably temporarily rewrite the primary rule to ignore the extra stuff, as follows:
```
primary[expr_ty]: [AWAIT] a=atom ('.' NAME | '[' slices ']' | '(' [arguments] ')')* { a }
```
That's totally bogus if there's more than just an atom, but so is calling CONSTRUCTOR().

**Comment by gvanrossum** [comment]
FWIW the primary rule is one where I think we would be better off using left-recursion.
```
primary[expr_ty]:
    | AWAIT primary
    | primary '.' NAME
    | primary '[' slices ']'
    | primary '(' [arguments] ')'
    | atom
```

**Comment by lysnikolaou** [comment]
That's a good idea. I think, that would be nicer as well.

On another note:
I think that `disjunction` and `conjunction` are rules, where looping is better that left-recursion, due to the fact the `BoolOp` just takes an `asdl_seq *` with all the operands as an argument, which is more easily constructed with a loop. Do you agree or is it just me?

On yet another note:
Should I maybe do some other part of the Grammar? It seemed like a good idea to have `BinOp`s and `BoolOp`s, so that we can test other rules that require expressions but we can always just use a `NAME` token for now. Would it be easier to go from the bottom up?

**Comment by gvanrossum** [comment]
> I think that disjunction and conjunction are rules, where looping is better that left-recursion

Agreed. (Even though this is an artifact of the current AST structure. But let's not fight that yet.)

> Would it be easier to go from the bottom up?

I've been wondering. Though really, I think you can tackle things in almost any order, even middle-out.

**Comment by lysnikolaou** [comment]
Forgot to close this via the PR's commit message.
