### ISSUE TITLE
Write a function to compare the abstract aspect of AST

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#89]
A discussion about comparing AST in SO:
https://stackoverflow.com/a/59144406/545637

**Comment by lysnikolaou** [comment]
As mentioned in the answer, when comparing two ASTs with `ast.dump(a) == ast.dump(b)`, the default behaviour is to only compare the generated nodes, without taking into consideration the metadata about line numbers and column offsets. Do you intend to to something other than that? Maybe compare the AST objects without converting them to strings?

**Comment by gvanrossum** [comment]
You can use `ast.dump(node, include_attributes=True)` to get the line/col numbers.
