### ISSUE TITLE
What should be included in the docs?

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#91]
I'm in the process of writing some really simple docs. What I've done so far is write some basic docs for all the external helper functions and all the helper structs, "stealing" some of the things written in `notes.md`.

I've also created a file called `grammar.py`, but I've only described the styling I'm using when refactoring the grammar rules. 

Do you maybe have any other ideas on what should be included in these early-stage docs?

**Comment by gvanrossum** [comment]
What’s in grammar.py?

Docs should also describe the grammar format.

**Comment by lysnikolaou** [comment]
I meant `grammar.md`. Should all the different grammar constructs like Optionals, Repeats and so on be listed and documented here?

**Comment by gvanrossum** [comment]
That’s the idea, yes.
